server:
  port: 9800
spring:
  application:
    name: @artifactId@

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.cloud.admin.beans
  global-config:
    banner: false
    db-config:
      id-type: id_worker
      field-strategy: not_empty
      column-underline: true
      #capital-mode: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

security:
  oauth2:
    resourceId: admin
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://cloud-auth/oauth/token
      user-authorization-uri: http://cloud-auth/oauth/authorize
      ignore-urls:
        - /v2/api-docs
        - /swagger-resources
        - /swagger-resources/**
        - /configuration/ui
        - /configuration/security
        - /swagger-ui.html
        - /webjars/**
        - /genscheme/generator/**
    resource:
      token-info-uri: http://cloud-auth/oauth/check_token
      loadBalanced: true


swagger:
  enabled: true
  author: Hcloud
  title: Hcloud SpringCloud
  desc: Hcloud SpringCloud doc
  version: v2.0
  termsOfServiceUrl: http://www.eduvipx.cn/termsOfServiceUrl
  host: 127.0.0.1:9999
  authUri: http://127.0.0.1:9999/auth/oauth/token

logging:
  config: classpath:logback-spring.xml
  level:
    com.cloud.admin.api.IDictService: debug

info:
  name: @project.artifactId@
  description: @project.description@
  version: @project.version@
